; Switches
melee_mainhand := "j"
excalibur := "k"
sgb := "l"
mainhand := "]"
offhand := "["
shield := "\"
helm := "l"
body := "."
legs := "Delete"
boots := "8"
flank := "o"
hybrid_2h := "4"
2h := "i"
pf := "Z"
hybrid_prayer := "H"
ranged_prayer := "Home"
mage_prayer := "Ins"
apot := "V"

; Abilities
bladed_dive := "3"
ingen := "5"
deto := "e"
omni := "y"
special_attack := "6"
auto := ":"
surge := "1"
eof := "u"
wild_magic := "r"
ice_blitz := "4"
gconc := "s"
limitless := "!"
tendril := "W"
ingen := "5"
asphyx :="t"

;Spells
blood_barrage := ";"
ice_barrage := "'"
smoke_cloud := "h"
ice_blitz := "4"
swap := "="
venge := "9"
disrupt := "0"

